### PR TITLE
Fixing defaults for Ubuntu with MongoDB >= 2.6

### PR DESCRIPTION
**Pull request by luishdez**
Source: https://github.com/edelight/chef-mongodb/pull/371

### CODE REVIEW

**Comment by josephholsten** [comment]
:+1: LGTM

is this worth adding a test for?

**Comment by triccardi-systran** [comment]
:-1: `node['version']` does *not* contains mongodb version: it isn't even defined (direct children of `node` are usually filled by ohai with OS information, nothing more). @jperville was right [in the original discussion](https://github.com/edelight/chef-mongodb/pull/371#commitcomment-10931716) for that part. (I tested by adding logs in `attributes/default.rb`)

However `node['mongodb']['version']` is not filled either...

The fix will probably require adding an explicit `node['mongodb']['version']`, which would be a first step to handle mongodb 3.0; I don't know how we could auto-detect the version otherwise. And as we have multiple installation methods which can install any version we cannot guess the default version either...

**Comment by jperville** [comment]
Thank you very much :)

**Comment by luishdez** [comment]
I'm ok with adding an explicit `node['mongodb']['version']` and I also think this could help the update for 3.0 it will simplify things

**Comment by shortdudey123** [comment]
Closing since this will be handled in the rewrite for 3.x

**Pull request closed without merging**
