### PR TITLE
Fixing all Rubocop lint warnings

### PR DESCRIPTION
**Pull request by rex**

### CODE REVIEW

**Comment by rex** [comment]
@josephholsten @luishdez Can I get your eyes on this? I'm still working my way through the codebase and don't want to break anything unwittingly.

Side note: How have you guys been running the tests? `rake -T` gives me a huge number of kitchen tests to run, but I definitely don't have time at the moment to run 4 hours of spin-up-configure-spin-down vagrant builds.

**Comment by josephholsten** [comment]
@rex I usually only run against a single kitchen test to verify the thing is fixed on the platform I'm trying to work on. I switch around occasionally to avoid breaking stuff, but usually you'll know if you're doing something that will break other platforms.

**Comment by josephholsten** [comment]
The main caveat I have for this: you will probably "break" all open PRs.

**Comment by josephholsten** [comment]
:+1: LGTM

**Comment by zarry** [comment]
I can dedicate some cycles for tests this evening.  Would you like me to run off master?

**Comment by zarry** [comment]
LGTM although @josephholsten brings up a good point and I think we should try to get some more of the open PRs through and then circle back for this.  Just to make life a bit easier.

**Comment by rex** [comment]
@josephholsten @zarry You guys are both right. It would be easier and cause fewer conflicts to circle back on this after more of these PRs are accepted and merged. Tabling this for now, no need to spend any cycles :)

**Comment by zarry** [comment]
@rex I ran some tests and things aren't in the best place.  I had many failures and failures were causing exit on the concurrent test_kitchen run oddly enough.  I am going to create a separate issue for documenting and working through all the test kitchen cases. Likely there will be a handful of PRs off of that resolving issues found during test kitchen runs.

**Comment by rex** [comment]
@zarry Thank you for the heads up. I think one of the first orders of business here is refactoring the tests to ensure that Travis doesn't mark a build as passing when it's really failing. Ahem. 

I'll see if I can get some of that done this morning but it will likely be afternoon before I get some cycles to work on it.

**Comment by luishdez** [comment]
LGTM as @josephholsten says, it could cause some conflicts with existing PRs, my initial idea was to clean all those PRs to avoid conflicts with new updates. Anyways doesn't look as a big change so it won't be too much problem.

**Comment by josephholsten** [comment]
@rex at this point, I'd rather get what we can merged than delay. Care to merge?

**Comment by tas50** [comment]
We should probably just close this out at this point and run a cookstyle -a on the current state of the repo

**Comment by shortdudey123** [comment]
Closing since this is pretty outdated and i am covering this in the rewrite branch

**Pull request closed without merging**
