### PR TITLE
mongodb_instance: remove mongodb_type, update recipes

### PR DESCRIPTION
**Pull request by josephholsten**
pretty much what it says on the tin.

I added the `mongodb_type` to add a bit of sanity long ago when I was trying to convert `mongodb_instance` to a resource the first (or hundredth?) time. After updating my resourcification branch, I see it's not needed.

### CODE REVIEW

**Comment by josephholsten** [comment]
oh, the *reason* this is required for #44 is that current calls to `mongodb_instance` use the `mongodb_type`, `enablerest` and `smallfiles` params, which will not be included in the LWRP

**Comment by josephholsten** [comment]
here's the easy to read version: https://github.com/chef-brigade/mongodb-cookbook/pull/45/files?w=1

@luishdez, @rex how's this look?

**Comment by damacus** [comment]
I think we need some test to make sure this doesn't blow anything up before merging this in any further. 

@josephholsten if you're happy I'm going to close his off now.

**Comment by shortdudey123** [comment]
Closing
will be tracked in https://github.com/sous-chefs/mongodb/pull/44 after the v1 rewrite

**Pull request closed without merging**
