### PR TITLE
Force SHA-1 mechanism while creating SCRAM user credentials

### PR DESCRIPTION
**Pull request by stissot**
## Description

We force SCRAM SHA-1 authentication mechanism during user creation, because the mongo ruby gem forces digestPassword=false and this is not compatible with the default SCRAM SHA-256 (server side digest) which is the default from MongoDB 4.0

mongo ruby gem, as of 1.12.5, forces digestPassword to be false,
which is not supported by SCRAM SHA-256 used by default on MongoDB >=4.0

### Issues Resolved

Fix for the user creation problem with MongoDB 4.0+ reported in #200

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by stissot** [comment]
One test if failing because the Chef EULA is not accepted in the CircleCI/lint job, but this is not related to the current issue, can someone fix this?

**Comment by Xorima** [comment]
Hey @stissot 

Apologies for the delayed review, you have a couple test failures now (the EULA has been resolved) so could you just do a sanity check that this works please?

If you need help with anything drop by #sous-chefs channel in https://community-slack.chef.io/

**Comment by stissot** [comment]
@Xorima: I see you have just rebased the PR from master. The failing tests/errors are the same than on master and not related to my changes. You should first fix the failing tests on the master branch, then let me know and I can sync the `mongodb4_authmech` branch again and we will see if the tests pass.

**Comment by Xorima** [comment]
@stissot 

We could do that or I can just merge it, failing tests are not your problem (unless you want to fix them for us :smile: ) 

Thanks for this, I will look to get a release out later today

**Pull request merged**
