### PR TITLE
Ubuntu 18 requires Mongo 4.

### LINKED ISSUE #209: No candidate version available for mongodb-org
### Cookbook version
1.2.0

### Chef-client version
14.4.56

### Platform Details
Ubuntu 18.04, ec2, t2.micro

### Scenario:
Trying to install mongodb using the cookbook

### Steps to Reproduce:
Just include the mongodb install recipe

### Expected Result:
mongodb should be smoothly installed

### Actual Result:

This is the error stacktrace

```
[myserver.com] * apt_package[mongodb-org] action install
[myserver.com] [2018-10-03T06:57:51+00:00] INFO: Processing apt_package[mongodb-org] action install (sc-mongodb::install line 114)
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] * No candidate version available for mongodb-org
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] ================================================================================
[myserver.com]
[myserver.com]
[myserver.com] Error executing action `install` on resource 'apt_package[mongodb-org]'
[myserver.com]
[myserver.com]
[myserver.com] ================================================================================
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] Chef::Exceptions::Package
[myserver.com]
[myserver.com]
[myserver.com] -------------------------
[myserver.com]
[myserver.com]
[myserver.com] No candidate version available for mongodb-org
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] Resource Declaration:
[myserver.com]
[myserver.com]
[myserver.com] ---------------------
[myserver.com]
[myserver.com]
[myserver.com] # In /tmp/chefcache/cookbooks/sc-mongodb/recipes/install.rb
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] 114: package node['mongodb']['package_name'] do
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] 115:   options node['mongodb']['packager_options']
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] 116:   action :install
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] 117:   version package_version
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] 118:   not_if { node['mongodb']['install_method'] == 'none' }
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] 119: end
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] 120:
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] Compiled Resource:
[myserver.com]
[myserver.com]
[myserver.com] ------------------
[myserver.com]
[myserver.com]
[myserver.com] # Declared in /tmp/chefcache/cookbooks/sc-mongodb/recipes/install.rb:114:in `from_file'
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] apt_package("mongodb-org") do
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]   package_name "mongodb-org"
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]   action [:install]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]   default_guard_interpreter :default
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]   declared_type :package
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]   cookbook_name "sc-mongodb"
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]   recipe_name "install"
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]   options ["-o", "Dpkg::Options::=--force-confold", "--force-yes"]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]   version "3.6.1"
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]   not_if { #code block }
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] end
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] System Info:
[myserver.com]
[myserver.com]
[myserver.com] ------------
[myserver.com]
[myserver.com]
[myserver.com] chef_version=14.4.56
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] platform=ubuntu
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] platform_version=18.04
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] program_name=/usr/local/bin/chef-client
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com] executable=/usr/local/bin/chef-client
[myserver.com]
[myserver.com]
[myserver.com]
[myserver.com]
```

### PR DESCRIPTION
**Pull request by mrala**
- Add Ubuntu 18 in test-kitchen
- Use [Mongo 4.0.3](http://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/) for Ubuntu 18 since 3.x is unavailable

Resolves #209

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by mrala** [comment]
Working on getting all of the test suites to pass.

**Comment by josephholsten** [comment]
Thank you so much @mrala, do you need anything from us at this point?

**Comment by mrala** [comment]
Trying to figure out why some tests are failing on Travis CI even though they're passing locally.

**Comment by josephholsten** [comment]
At least one of these is a timeout. We can force a rebuilt of those tests for now, and engage @damacus's circleci wizardry for a permanent solution.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/mongodb/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mrala** [comment]
Some tests are still failing on circle-ci but they are passing locally.

**Comment by damacus** [comment]
How is that test passing locally? 🤔

**Comment by damacus** [comment]
This requires the new CircleCI orb version (`@2`) for this pipeline to work. If you can get that working separately that'd be great 👍 

Closing for now as this hasn't been touched in a few months

**Pull request closed without merging**
