### PR TITLE
Add retries in user_management.rb

### PR DESCRIPTION
**Pull request by luishdez**
Source: https://github.com/edelight/chef-mongodb/pull/381

### CODE REVIEW

**Comment by luishdez** [comment]
IMHO It doesn't feel like the right way to confirm that a service is running. We should check `status => true` and other ways.

**Comment by zarry** [comment]
I agree but in the same breath it is not only making sure the service running but making sure it is connectable before it attempts to connect.  Is there a case if we were checking service mongod status where we would receive a message saying it is start/running but it still may not be connectable?

**Comment by luishdez** [comment]
I think the action to start services in chef won't continue until it gets the `exit 0` or fail and I think after that moment you can connect to mongo. I haven't tested though

**Comment by triccardi-systran** [comment]
I don't think there is a standard way for a process to notify its parent that it's ready to serve its purpose.
So I don't know how mongod could notify start-stop-daemon (for old sysvinit) that it can exit 0 and guarantee that mongod can accept connections.

3a91a2822fd4acc99a6e570c7927a15e9a341d58 tries to implement this by trying to connect to the tcp port via `netcat` and abort after 20 tries. It's only done for the debian sysvinit service definition.
There is no such thing for upstart or systemd scripts.
I think it should be done in chef directly, only once: it would work for all services implementations for free. I'm not sure how it could be done though. (Maybe with a notify immediate on the service resource that try in loop? We would need a guarantee that it's executed before any other notification, even the immediate ones, I don't know if it's possible...)
We could then use the ruby mongo client and have more flexibility than running a process (in the future we could only install the mongod package and not the cli client, this would break with this PR).

In fact this is more complex than that: it seems possible to have a mongod accepting TCP connections but not ready to handle them all. See edelight/chef-mongodb#376 for example.

**Comment by shortdudey123** [comment]
Closing since this blindly restarts mongo on every time this recipe is run and does not take into account port in the `mongo` call

Probably better to put verification into the `mongodb_user` side of things

**Pull request closed without merging**
