### PR TITLE
Use the replicaset name as the prefix

### PR DESCRIPTION
**Pull request by luishdez**
Source: https://github.com/edelight/chef-mongodb/pull/253

### CODE REVIEW

**Comment by josephholsten** [comment]
@luishdez I think we stalled on this in the past because it's backwards incompatible. Otherwise LGTM.

**Comment by luishdez** [comment]
I'm ok with this one :+1: 

It breaks BC but we have tags and releases for that

We should add a note to a CHANGELOG.md for the new release

Fix: https://github.com/edelight/chef-mongodb/issues/347
Fix: https://github.com/edelight/chef-mongodb/issues/6

**Comment by josephholsten** [comment]
@rex thoughts?

**Comment by shortdudey123** [comment]
carried into https://github.com/sous-chefs/mongodb/pull/155

**Pull request closed without merging**
