### PR TITLE
Add `netcat` package for debian init script

### PR DESCRIPTION
**Pull request by scopenco**
Debian official box `debian/contrib-stretch64` doesn't have `netcat` package that is required by the debian init script.

### CODE REVIEW

**Comment by scopenco** [comment]
This is about debian official vagrant box https://app.vagrantup.com/debian/boxes/contrib-stretch64

**Comment by damacus** [comment]
We don't use those boxes though do we? Don't we use the ones @cheeseplus builds

**Comment by scopenco** [comment]
This thing is to add support of other boxed and official distro. Without this package installed, the cookbook will fail.

**Comment by scopenco** [comment]
@damacus can you release a patch version to the supermarket?

**Pull request merged**
