### PR TITLE
Allow for single member replica sets in chef-server mode, force sharding configuration in mongos recipe

### PR DESCRIPTION
**Pull request by luishdez**
Source: https://github.com/edelight/chef-mongodb/pull/282

### CODE REVIEW

**Comment by damacus** [comment]
@shortdudey123 are we going to pull this in as part of the rewrite?

**Comment by shortdudey123** [comment]
Yes, i will merge this in as part of the rewrite

**Comment by damacus** [comment]
@shortdudey123 ping reminder about this one.

**Comment by shortdudey123** [comment]
yeah, need to pull this in

**Comment by shortdudey123** [comment]
Superseded by https://github.com/sous-chefs/mongodb/issues/158

**Pull request closed without merging**
